(() => {
  const API_BASE = (window.ACCUMULATION_API_BASE || '').replace(/\/$/, '');
  const staticPages = !API_BASE && /github\.io$/i.test(location.hostname);
  const KEY = 'vikram-owner-key'; const SCANNER_ID = 'accumulation';
  const $ = id => document.getElementById(id);
  const ownerKey = () => { let k = localStorage.getItem(KEY); if (!k) { k = 'local-' + crypto.randomUUID(); localStorage.setItem(KEY,k); } return k; };
  const api = async (path, options={}) => { const r = await fetch(API_BASE + path, { ...options, headers:{'Content-Type':'application/json','x-vikram-user':ownerKey(),...(options.headers||{})} }); const b=await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.error||`Request failed (${r.status})`); return b; };
  function backendNotice(){ if(!staticPages)return true; $('backendNotice').classList.remove('hidden'); $('backendNotice').innerHTML='<strong>Alerts require the live VIKRAM backend.</strong> Connect this page to the deployed API through <code>window.ACCUMULATION_API_BASE</code>.'; return false; }
  async function load(){ const {preferences=[]}=await api('/api/alerts/preferences'); const p=preferences.find(x=>x.scanner_id===SCANNER_ID); $('emailToggle').checked=!!p?.email_enabled; $('pushToggle').checked=!!p?.push_enabled; if(ownerKey().includes('@')) $('emailInput').value=ownerKey(); await history(); }
  async function save(){ const emailOn=$('emailToggle').checked, email=$('emailInput').value.trim(); if(emailOn&&!email.includes('@')) return alert('Enter a valid email address.'); if(emailOn)localStorage.setItem(KEY,email); await api('/api/alerts/preferences',{method:'POST',body:JSON.stringify({scannerId:SCANNER_ID,emailEnabled:emailOn,pushEnabled:$('pushToggle').checked})}); await load(); alert('Preferences saved.'); }
  function b64(s){const p='='.repeat((4-s.length%4)%4);return Uint8Array.from(atob((s+p).replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));}
  async function push(){ if(!('serviceWorker'in navigator&&'PushManager'in window))return $('pushStatus').textContent='Push: UNSUPPORTED.'; try{if(await Notification.requestPermission()!=='granted')throw new Error('Browser permission not granted.');const {publicKey}=await api('/api/push/vapid-public-key');const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(publicKey)});await api('/api/push/subscribe',{method:'POST',body:JSON.stringify({subscription:sub.toJSON()})});$('pushStatus').textContent='Push: ENABLED on this browser.';}catch(e){$('pushStatus').textContent=`Push: FAILED — ${e.message}`;}}
  async function history(){try{const {history=[]}=await api('/api/alerts/history');$('historyMeta').textContent=`${history.length} record(s)`;$('historyRows').innerHTML=history.length?history.map(h=>`<tr><td>${h.symbol}</td><td>${h.scanner_id}</td><td>${h.channel}</td><td>${h.status}</td><td>${h.error||'—'}</td><td>${new Date(h.created_at).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="6" class="text-muted">No alerts yet.</td></tr>';}catch(e){$('historyRows').innerHTML=`<tr><td colspan="6">${e.message}</td></tr>`;}}
  if(backendNotice()) { $('savePrefBtn').onclick=save; $('enablePushBtn').onclick=push; load().catch(e=>console.warn(e)); }
})();