(()=>{'use strict';
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const sym=()=>String(new URLSearchParams(location.search).get('symbol')||new URLSearchParams((location.hash||'').replace(/^#/,'')).get('symbol')||'').trim().toUpperCase();
const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v==null||v===''?'N/A':v};
const css=()=>{if(document.getElementById('researchRepairCss'))return;const s=document.createElement('style');s.id='researchRepairCss';s.textContent=`body.research-focus-layout{overflow-x:hidden}.research-focus-layout .workspace-layout{grid-template-columns:minmax(0,1fr)!important;width:100%!important;max-width:none!important}.research-focus-layout .workspace-layout>.sidebar,.research-focus-layout .workspace-layout>.right-feed{display:none!important}.research-focus-layout .main-content{width:100%!important;max-width:none!important;min-width:0!important;padding-left:clamp(18px,4vw,64px)!important;padding-right:clamp(18px,4vw,64px)!important}.research-focus-layout .company-overview{width:100%!important}.research-focus-layout #companyOverview{width:100%!important}.research-focus-layout .vd-research-note{display:block}`;document.head.appendChild(s)};
async function load(){try{if(window.VIKRAM_DATA_ENGINE?.loadSnapshot)return await window.VIKRAM_DATA_ENGINE.loadSnapshot();const r=await fetch('data/scanner.json',{cache:'no-store'});if(!r.ok)return null;return await r.json()}catch(_){return null}}
async function repair(){const ticker=sym();if(!ticker)return;css();document.body.classList.add('research-focus-layout');const s=await load();const row=s?.results?.find(r=>String(r.symbol||r.ticker||'').toUpperCase()===ticker);let score=num(row?.score);let verdict=String(row?.verdict||'').toUpperCase();if(score==null&&window.VIKRAM_DATA_ENGINE?.find){const found=window.VIKRAM_DATA_ENGINE.find(ticker);score=num(found?.score);verdict=String(found?.verdict||verdict).toUpperCase()}if(score==null&&window.VIKRAM_DATA_ENGINE?.analyzeAsset){const a=window.VIKRAM_DATA_ENGINE.analyzeAsset(ticker);score=num(a?.meta?.accumulationScore);verdict=String(a?.meta?.accumulationVerdict||verdict).toUpperCase()}const label=document.getElementById('overviewVikramScore')?.previousElementSibling;if(label)label.textContent='Accumulation Score';if(score!=null)set('overviewVikramScore',score.toFixed(1));if(verdict)set('overviewRating',verdict);const card=document.getElementById('companyOverview');if(card){let n=card.querySelector('.research-source-note');if(!n){n=document.createElement('small');n.className='research-source-note';n.style.cssText='display:block;margin-top:6px;color:var(--text-muted);font-size:9px;font-weight:700';card.appendChild(n)}n.textContent=`Source: Accumulation Scanner • ${row?.tradeDate||'verified EOD snapshot'} • EOD VERIFIED. Research fundamentals remain N/A until a verified fundamentals dataset exists.`}}
function boot(){repair().catch(()=>{});[250,1000,2500,5000].forEach(ms=>setTimeout(()=>repair().catch(()=>{}),ms))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
