(() => {
  const root=document.getElementById('ruleRoot'); if(!root)return;
  let seq=0; const id=()=>++seq;
  const fields=[['score','VIKRAM Score'],['metrics.close','Close'],['metrics.volume','Volume'],['metrics.deliveryPct','Delivery %'],['metrics.volumeRatio','Volume Ratio'],['metrics.changeOi','OI Change'],['technical.rsi14','RSI 14'],['technical.ema20','EMA 20'],['technical.ema50','EMA 50'],['technical.obv','OBV']];
  let tree={id:id(),type:'group',operator:'AND',rules:[{id:id(),type:'condition',left:{type:'field',name:'score'},operator:'>=',right:70}]};
  const opts=(sel)=>fields.map(([v,l])=>`<option value="${v}" ${v===sel?'selected':''}>${l}</option>`).join('');
  const renderNode=n=>n.type==='condition'?`<div class="rb-node" data-id="${n.id}"><select class="rb-left">${opts(n.left.name)}</select><select class="rb-op"><option>>=</option><option>></option><option><=</option><option><</option><option>==</option><option>!=</option></select><select class="rb-right-field"><option value="__value">Fixed value</option>${opts('__field')}</select><input class="rb-value" type="text" value="${n.right?.type==='field'?'':String(n.right??'70')}"><button class="rb-remove">×</button></div>`:`<div class="rb-group" data-id="${n.id}"><div><select class="rb-group-op"><option ${n.operator==='AND'?'selected':''}>AND</option><option ${n.operator==='OR'?'selected':''}>OR</option><option ${n.operator==='NOT'?'selected':''}>NOT</option></select><button class="rb-add-cond">+ Condition</button><button class="rb-add-group">+ Group</button></div>${n.rules.map(renderNode).join('')}</div>`;
  function render(){root.innerHTML=renderNode(tree);bind(root);}
  function find(n,target){if(n.id===target)return n;if(n.rules)for(const c of n.rules){const x=find(c,target);if(x)return x}return null}
  function remove(n,target){if(!n.rules)return false;const i=n.rules.findIndex(x=>x.id===target);if(i>=0){n.rules.splice(i,1);return true}return n.rules.some(c=>remove(c,target));}
  function bind(scope){scope.querySelectorAll('.rb-group-op').forEach(el=>el.onchange=()=>{find(tree,Number(el.closest('.rb-group').dataset.id)).operator=el.value;});scope.querySelectorAll('.rb-add-cond').forEach(el=>el.onclick=()=>{find(tree,Number(el.closest('.rb-group').dataset.id)).rules.push({id:id(),type:'condition',left:{type:'field',name:'score'},operator:'>=',right:70});render()});scope.querySelectorAll('.rb-add-group').forEach(el=>el.onclick=()=>{find(tree,Number(el.closest('.rb-group').dataset.id)).rules.push({id:id(),type:'group',operator:'AND',rules:[{id:id(),type:'condition',left:{type:'field',name:'score'},operator:'>=',right:70}]});render()});scope.querySelectorAll('.rb-remove').forEach(el=>el.onclick=()=>{remove(tree,Number(el.closest('.rb-node').dataset.id));render()});scope.querySelectorAll('.rb-node').forEach(el=>{const n=find(tree,Number(el.dataset.id));el.querySelector('.rb-left').onchange=e=>n.left={type:'field',name:e.target.value};el.querySelector('.rb-op').onchange=e=>n.operator=e.target.value;el.querySelector('.rb-right-field').onchange=e=>{if(e.target.value==='__value')n.right=70;else n.right={type:'field',name:e.target.value};render()};el.querySelector('.rb-value').onchange=e=>{if(n.right&&typeof n.right==='object')return;n.right=Number.isFinite(Number(e.target.value))?Number(e.target.value):e.target.value;};});}
  const clean=n=>n.type==='condition'?{type:'condition',left:n.left,operator:n.operator,right:n.right}:{type:'group',operator:n.operator,rules:n.rules.map(clean)};
  document.getElementById('runBtn').onclick=async()=>{const snap=await window.VIKRAM_DATA_ENGINE.loadSnapshot();const matches=(snap.results||[]).map(r=>({r,e:window.VIKRAM_RULE_ENGINE.eval(clean(tree),r)})).filter(x=>x.e.result===true).slice(0,100);document.getElementById('matchMeta').textContent=`${matches.length} matches`;document.getElementById('matchResults').innerHTML=matches.length?matches.map(x=>`<tr><td><strong>${x.r.symbol}</strong></td><td>${x.r.score??'N/A'}</td><td>${x.r.verdict??'N/A'}</td><td>${x.e.reason}</td></tr>`).join(''):'<tr><td colspan="4">No verified matches.</td></tr>';};
  document.getElementById('saveBtn').onclick=()=>{const name=prompt('Name this scan');if(!name)return;const saved=JSON.parse(localStorage.getItem('vikram-saved-scans')||'[]');saved.push({name,rule:clean(tree),savedAt:new Date().toISOString()});localStorage.setItem('vikram-saved-scans',JSON.stringify(saved));renderSaved()};
  function renderSaved(){const s=JSON.parse(localStorage.getItem('vikram-saved-scans')||'[]');document.getElementById('savedScans').innerHTML=s.length?s.map((x,i)=>`<button class="btn" data-load="${i}">${x.name}</button>`).join(' '):'No saved scans yet.';document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const x=s[Number(b.dataset.load)];tree=JSON.parse(JSON.stringify(x.rule));seq=0;render()})}
  render();renderSaved();
})();
