(()=>{'use strict';
async function boot(){
const surface=document.querySelector('.scanner-container-surface');if(!surface)return;
const remove=()=>{surface.querySelector('.filter-controls')?.remove();surface.querySelector('.vikram-segment-filters')?.remove();document.querySelectorAll('.vikram-simple-filter,.vikram-column-filter,.vikram-column-menu,.vikram-filter-reset').forEach(e=>e.remove())};
const r=await fetch('data/scanner.json',{cache:'no-store'});if(!r.ok)return;const snap=await r.json();if(snap?.dataStatus!=='EOD VERIFIED'||!Array.isArray(snap.results))return;
remove();
const firstTab=surface.querySelector('.surface-tab');if(firstTab){firstTab.textContent='★ Accumulation Scanner';firstTab.classList.add('active');firstTab.click()}
if(!surface.querySelector('.scanner-heading-row')){const meta=surface.querySelector('.scanner-meta');const heading=document.createElement('div');heading.className='scanner-heading-row';heading.innerHTML='<div><span class="eyebrow">PRIMARY SCANNER</span><h2>Accumulation Scanner</h2><p>Verified EOD accumulation evidence across the supported NSE universe. Click any column heading to sort.</p></div><div class="scanner-status-pill">EOD VERIFIED · NOT LIVE</div>';meta?.after(heading)}
if(!surface.querySelector('.scanner-summary-grid')){const heading=surface.querySelector('.scanner-heading-row');const summary=document.createElement('div');summary.className='scanner-summary-grid';summary.innerHTML='<div class="scanner-summary scanner-summary-green"><strong id="scannerConfirmedCount">—</strong><span>Accumulation Confirmed</span></div><div class="scanner-summary scanner-summary-blue"><strong id="scannerStartingCount">—</strong><span>Accumulation Starting</span></div><div class="scanner-summary scanner-summary-gold"><strong id="scannerStrongCount">—</strong><span>Score 75+</span></div><div class="scanner-summary scanner-summary-neutral"><strong id="scannerResultCount">—</strong><span>Verified universe</span></div>';heading?.after(summary)}
if(!surface.querySelector('.scanner-legend')){const summary=surface.querySelector('.scanner-summary-grid');const legend=document.createElement('div');legend.className='scanner-legend';legend.setAttribute('aria-label','Scanner color legend');legend.innerHTML='<span>● Strong / positive</span><span>● Neutral / warning</span><span>● Weak / negative</span><span>● Starting</span><span>● Quiet absorption</span>';summary?.after(legend)}
let pager=surface.querySelector('.scanner-pager');if(!pager){pager=document.createElement('div');pager.className='scanner-pager';pager.setAttribute('aria-label','Accumulation Scanner pagination');surface.querySelector('.scanner-table-wrap')?.after(pager)}
const tbody=surface.querySelector('.scanner-table tbody');if(!tbody)return;
const N=v=>{const n=Number(v);return Number.isFinite(n)?n:null}, esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), pct=v=>{const n=N(v);return n==null?'N/A':`${n>=0?'+':''}${n.toFixed(2)}%`}, mult=v=>{const n=N(v);return n==null?'N/A':`${n.toFixed(2)}x`}, trend=v=>{const n=N(v);return n==null?'N/A':n>0?'Rising':n<0?'Falling':'Flat'}, cls=(k,v)=>{const n=N(v);if(k==='change'||k==='obv'||k==='oi')return n==null?'scanner-neutral':n>0?'scanner-positive':n<0?'scanner-negative':'scanner-neutral';if(k==='score')return n==null?'scanner-neutral':n>=75?'scanner-strong':n>=55?'scanner-warning':'scanner-weak';if(k==='volume')return n==null?'scanner-neutral':n>=1.2?'scanner-strong':n>=.8?'scanner-warning':'scanner-weak';if(k==='delivery')return n==null?'scanner-neutral':n>=55?'scanner-strong':n>=45?'scanner-warning':'scanner-weak';if(k==='verdict'){const x=String(v||'').toUpperCase();return x.includes('CONFIRMED')?'scanner-strong':x.includes('STARTING')?'scanner-starting':x.includes('QUIET')?'scanner-quiet':x.includes('DISTRIBUTION')?'scanner-negative':'scanner-neutral'}return ''};
const rows=[...new Map(snap.results.map(x=>{const m=x.metrics||{};const symbol=String(x.symbol||x.ticker||x.stock||'').toUpperCase();return[symbol,{symbol,name:x.name||x.companyName||x.company_name||symbol,price:N(m.close),change:N(m.priceChangePct),score:N(x.score),volume:N(m.volumeRatio),delivery:N(m.deliveryPct),obv:N(m.obvTrend),oi:N(m.changeOi),verdict:String(x.verdict||'N/A')}]}).filter(x=>x[0])).values()];
let key='score',dir=-1,page=1;const size=25;const sorted=()=>[...rows].sort((a,b)=>{if(key==='symbol'||key==='verdict')return dir*String(a[key]).localeCompare(String(b[key]));const av=N(a[key]),bv=N(b[key]);if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return -1;return dir*(av-bv)});
const draw=()=>{remove();const data=sorted(),pages=Math.max(1,Math.ceil(data.length/size));page=Math.min(page,pages);const visible=data.slice((page-1)*size,page*size);tbody.innerHTML=visible.map(x=>`<tr data-symbol="${esc(x.symbol)}"><td><strong>${esc(x.name)}</strong><div>${esc(x.symbol)}</div></td><td>₹${x.price==null?'N/A':x.price.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td class="${cls('change',x.change)}">${pct(x.change)}</td><td class="${cls('score',x.score)}"><strong>${x.score==null?'N/A':x.score.toFixed(1).replace(/\.0$/,'')}</strong></td><td class="${cls('volume',x.volume)}">${mult(x.volume)}</td><td class="${cls('delivery',x.delivery)}">${pct(x.delivery)}</td><td class="${cls('obv',x.obv)}">${trend(x.obv)}</td><td class="${cls('oi',x.oi)}">${x.oi==null?'N/A':x.oi.toLocaleString('en-IN')}</td><td class="${cls('verdict',x.verdict)}"><strong>${esc(x.verdict)}</strong></td></tr>`).join('')||'<tr><td colspan="9" class="empty-cell">No verified scanner rows available.</td></tr>';pager.innerHTML=`<button type="button" class="scanner-page-btn" data-p="prev" ${page<=1?'disabled':''}>‹ Prev</button><span>Page ${page} of ${pages} · ${data.length} verified stocks</span><button type="button" class="scanner-page-btn" data-p="next" ${page>=pages?'disabled':''}>Next ›</button>`;pager.querySelector('[data-p="prev"]')?.addEventListener('click',()=>{if(page>1){page--;draw()}});pager.querySelector('[data-p="next"]')?.addEventListener('click',()=>{if(page<pages){page++;draw()}});surface.querySelectorAll('th[data-sort]').forEach(th=>{const i=th.querySelector('.scanner-sort');if(i)i.textContent=th.dataset.sort===key?(dir<0?'↓':'↑'):'↕';th.setAttribute('aria-sort',th.dataset.sort===key?(dir<0?'descending':'ascending'):'none')})};
surface.querySelectorAll('th[data-sort]').forEach(th=>{th.onclick=()=>{if(key===th.dataset.sort)dir*=-1;else{key=th.dataset.sort;dir=key==='symbol'||key==='verdict'?1:-1}page=1;draw()};th.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();th.click()}}});
const date=document.getElementById('scannerDataDate'),age=document.getElementById('scannerDataAge'),d=snap.asOf||snap.results.find(x=>x.tradeDate)?.tradeDate;if(date)date.textContent=d||'—';if(age&&d){const days=Math.max(0,Math.floor((Date.now()-new Date(`${d}T00:00:00Z`).getTime())/86400000));age.textContent=`${days} day${days===1?'':'s'} old`};
const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('scannerConfirmedCount',rows.filter(x=>x.verdict.toUpperCase().includes('CONFIRMED')).length.toLocaleString('en-IN'));set('scannerStartingCount',rows.filter(x=>x.verdict.toUpperCase().includes('STARTING')).length.toLocaleString('en-IN'));set('scannerStrongCount',rows.filter(x=>x.score!=null&&x.score>=75).length.toLocaleString('en-IN'));set('scannerResultCount',`${rows.length.toLocaleString('en-IN')} verified stocks · 25 per page`);
const style=document.createElement('style');style.id='scannerUiRepairCss';style.textContent='.scanner-container-surface .filter-controls,.scanner-container-surface .vikram-segment-filters,.scanner-container-surface .vikram-simple-filter,.scanner-container-surface .vikram-column-filter,.scanner-container-surface .vikram-column-menu,.scanner-container-surface .vikram-filter-reset{display:none!important}.scanner-container-surface .scanner-table th[data-sort]{cursor:pointer;user-select:none}.scanner-container-surface .scanner-table th[data-sort]:hover{color:var(--accent-cyan)}.scanner-positive{color:#22c55e!important;font-weight:900}.scanner-negative{color:#ef4444!important;font-weight:900}.scanner-neutral{color:#f59e0b!important;font-weight:900}.scanner-strong{color:#22c55e!important;font-weight:900}.scanner-warning{color:#f59e0b!important;font-weight:900}.scanner-weak{color:#ef4444!important;font-weight:900}.scanner-starting{color:#60a5fa!important;font-weight:900}.scanner-quiet{color:#a855f7!important;font-weight:900}';document.head.appendChild(style);
draw();
new MutationObserver(()=>{if(surface.querySelector('.filter-controls')||surface.querySelector('.vikram-segment-filters'))remove()}).observe(surface,{childList:true,subtree:true});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot().catch(()=>{}),{once:true});else boot().catch(()=>{});
})();
