/* VIKRAM Theme Engine — six canonical themes + Light/Dark/System mode. */
(function(){'use strict';
const THEME_KEY='vikram_user_theme',MODE_KEY='vikram_user_mode';
const THEMES={aurora:'Aurora',galaxy:'Galaxy',calm:'Calm',academic:'Academic',neoglass:'NeoGlass',duology:'Duology'};
const MODES={light:'Light',dark:'Dark',system:'System'};
function validTheme(v){return Object.prototype.hasOwnProperty.call(THEMES,v)?v:'aurora'}
function validMode(v){return Object.prototype.hasOwnProperty.call(MODES,v)?v:'system'}
function apply(){const theme=validTheme(localStorage.getItem(THEME_KEY));const mode=validMode(localStorage.getItem(MODE_KEY));const root=document.documentElement;root.dataset.theme=theme;root.dataset.mode=mode;root.style.colorScheme=mode==='light'?'light':mode==='dark'?'dark':'light dark';document.querySelectorAll('[data-vikram-theme]').forEach(b=>b.classList.toggle('active',b.dataset.vikramTheme===theme));document.querySelectorAll('[data-vikram-mode]').forEach(b=>b.classList.toggle('active',b.dataset.vikramMode===mode))}
function setTheme(v){localStorage.setItem(THEME_KEY,validTheme(v));apply()}
function setMode(v){localStorage.setItem(MODE_KEY,validMode(v));apply()}
function build(){const host=document.querySelector('.header-container');if(!host||document.querySelector('.vikram-theme-control'))return;const wrap=document.createElement('div');wrap.className='vikram-theme-control';wrap.setAttribute('aria-label','VIKRAM theme and display mode');const select=document.createElement('select');select.setAttribute('aria-label','Choose VIKRAM theme');Object.entries(THEMES).forEach(([key,name])=>{const o=document.createElement('option');o.value=key;o.textContent=name;select.appendChild(o)});select.value=validTheme(localStorage.getItem(THEME_KEY));select.addEventListener('change',()=>setTheme(select.value));wrap.appendChild(select);const modes=document.createElement('span');modes.className='vikram-theme-mode';Object.entries(MODES).forEach(([key,name])=>{const b=document.createElement('button');b.type='button';b.dataset.vikramMode=key;b.textContent=name;b.title=`${name} mode`;b.addEventListener('click',()=>setMode(key));modes.appendChild(b)});wrap.appendChild(modes);host.appendChild(wrap);apply()}
function normalizeNavigation(){const nav=document.querySelector('.app-navigation .nav-list');if(!nav)return;const path=location.pathname.toLowerCase();const items=[['Home','index.html'],['Analysis','index.html#companyOverview'],['Accumulation Scanner','accumulation.html'],['Hidden Gems','index.html#hiddenGemsPreview'],['Opportunity Radar','index.html#opportunityRadar'],['Portfolio','index.html#portfolio'],['About','about.html']];nav.innerHTML='';items.forEach(([text,href])=>{const li=document.createElement('li');const a=document.createElement('a');a.className='nav-link';a.textContent=text;a.href=href;li.appendChild(a);nav.appendChild(li)});const currentHash=location.hash.toLowerCase();let activeText='Home';if(path.endsWith('/accumulation.html'))activeText='Accumulation Scanner';else if(path.endsWith('/about.html'))activeText='About';else if(currentHash.includes('hiddengemspreview'))activeText='Hidden Gems';else if(currentHash.includes('opportunityradar'))activeText='Opportunity Radar';else if(currentHash.includes('portfolio'))activeText='Portfolio';else if(currentHash.includes('companyoverview'))activeText='Analysis';nav.querySelectorAll('a.nav-link').forEach(a=>a.classList.toggle('active',a.textContent.trim()===activeText));window.addEventListener('hashchange',()=>{const h=location.hash.toLowerCase();const t=h.includes('hiddengemspreview')?'Hidden Gems':h.includes('opportunityradar')?'Opportunity Radar':h.includes('portfolio')?'Portfolio':h.includes('companyoverview')?'Analysis':'Home';nav.querySelectorAll('a.nav-link').forEach(a=>a.classList.toggle('active',a.textContent.trim()===t))})}
window.initThemeEngine=function(){apply();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{build();normalizeNavigation()},{once:true});else{build();normalizeNavigation()}};
window.initThemeEngine();
})();
