const express=require('express');const {Pool}=require('pg');const {evaluate}=require('./scannerEngine');
const app=express();app.use(express.json());const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('sslmode=require')?{rejectUnauthorized:false}:undefined});
const watch=['ONGC','VBL','BSE','NMDC'];
async function scan(symbols){const q=await pool.query(`SELECT * FROM cm_eod WHERE symbol=ANY($1) AND series='EQ' ORDER BY symbol,trade_date`,[symbols]);const f=await pool.query(`SELECT DISTINCT ON(symbol,trade_date) symbol,trade_date,oi,change_oi FROM futures_eod WHERE symbol=ANY($1) AND expiry >= trade_date ORDER BY symbol,trade_date,expiry`,[symbols]);const fm=new Map(f.rows.map(x=>[`${x.symbol}|${x.trade_date.toISOString().slice(0,10)}`,x]));const by=new Map();for(const r of q.rows){if(!by.has(r.symbol))by.set(r.symbol,[]);by.get(r.symbol).push(r);}return symbols.map(s=>evaluate(s,by.get(s)||[],(by.get(s)||[]).length?fm.get(`${s}|${by.get(s)[by.get(s).length-1].trade_date.toISOString().slice(0,10)}`):null));}
app.get('/api/health',async(_req,res)=>{try{const r=await pool.query(`SELECT max(trade_date) AS d FROM cm_eod`);res.json({status:'ok',lastCmDate:r.rows[0].d});}catch(e){res.status(503).json({status:'error',error:e.message});}});
app.get('/api/scanner/watchlist',async(_req,res)=>res.json({symbols:watch}));
app.get('/api/scanner/scan',async(req,res)=>{try{const symbols=String(req.query.symbols||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);if(!symbols.length)return res.status(400).json({error:'Provide at least one symbol'});res.json({results:await scan(symbols),asOf:new Date().toISOString()});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/scanner/all',async(_req,res)=>{try{const u=await pool.query(`SELECT DISTINCT symbol FROM cm_eod WHERE series='EQ' ORDER BY symbol`);res.json({results:await scan(u.rows.map(x=>x.symbol)),asOf:new Date().toISOString()});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/stock/:symbol',async(req,res)=>{try{const s=req.params.symbol.toUpperCase();const q=await pool.query(`SELECT * FROM cm_eod WHERE symbol=$1 AND series='EQ' ORDER BY trade_date`,[s]);if(!q.rows.length)return res.status(404).json({error:'No verified EOD data for '+s});const last=q.rows[q.rows.length-1];const f=await pool.query(`SELECT symbol,trade_date,oi,change_oi FROM futures_eod WHERE symbol=$1 AND trade_date=$2 AND expiry >= trade_date ORDER BY expiry LIMIT 1`,[s,last.trade_date]);res.json({result:evaluate(s,q.rows,f.rows[0]||null)});}catch(e){res.status(500).json({error:e.message});}});
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`VIKRAM accumulation API listening on ${port}`));
