const { Pool } = require('pg');
const { parse } = require('csv-parse/sync');
const unzipper = require('unzipper');
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_URL?.includes('sslmode=require') ? { rejectUnauthorized:false } : undefined });
const HOME='https://www.nseindia.com';
const HEADERS={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/134.0 Safari/537.36','Accept':'*/*','Accept-Language':'en-US,en;q=0.9','Referer':HOME+'/'};
async function get(url){const r=await fetch(url,{headers:HEADERS});if(!r.ok)throw new Error(`NSE ${r.status} for ${url}`);return Buffer.from(await r.arrayBuffer());}
function clean(v){return v===undefined||v===null||String(v).trim()===''?null:String(v).trim();}
function num(v){const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:null;}
function parseCsv(buf){return parse(buf.toString('utf8').replace(/^\uFEFF/,''),{columns:true,skip_empty_lines:true,trim:true,relax_column_count:true});}
async function ingestCm(date){const ddmmyyyy=date.toISOString().slice(0,10).split('-').reverse().join('');const url=`https://nsearchives.nseindia.com/products/content/sec_bhavdata_full_${ddmmyyyy}.csv`;const rows=parseCsv(await get(url)).filter(r=>clean(r.SERIES)==='EQ');const client=await pool.connect();try{await client.query('BEGIN');for(const r of rows){await client.query(`INSERT INTO cm_eod(symbol,trade_date,series,prev_close,open,high,low,last_price,close,avg_price,volume,deliv_qty,deliv_per,turnover,no_of_trades) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(symbol,trade_date) DO UPDATE SET prev_close=EXCLUDED.prev_close,open=EXCLUDED.open,high=EXCLUDED.high,low=EXCLUDED.low,last_price=EXCLUDED.last_price,close=EXCLUDED.close,avg_price=EXCLUDED.avg_price,volume=EXCLUDED.volume,deliv_qty=EXCLUDED.deliv_qty,deliv_per=EXCLUDED.deliv_per,turnover=EXCLUDED.turnover,no_of_trades=EXCLUDED.no_of_trades`,[clean(r.SYMBOL),date.toISOString().slice(0,10),clean(r.SERIES),num(r.PREV_CLOSE),num(r.OPEN_PRICE),num(r.HIGH_PRICE),num(r.LOW_PRICE),num(r.LAST_PRICE),num(r.CLOSE_PRICE),num(r.AVG_PRICE),num(r.TTL_TRD_QNTY),num(r.DELIV_QTY),num(r.DELIV_PER),num(r.TURNOVER_LACS),num(r.NO_OF_TRADES)]);}await client.query(`INSERT INTO ingestion_runs(segment,trade_date,status,row_count,schema_version) VALUES('CM',$1,'success',$2,'cm-full-v1')`,[date.toISOString().slice(0,10),rows.length]);await client.query('COMMIT');return rows.length;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function ingestFo(date){const ymd=date.toISOString().slice(0,10).replaceAll('-','');const url=`https://nsearchives.nseindia.com/content/fo/BhavCopy_NSE_FO_0_0_0_${ymd}_F_0000.csv.zip`;const zip=await unzipper.Open.buffer(await get(url));const file=zip.files.find(f=>/\.csv$/i.test(f.path));if(!file)throw new Error('No CSV found in NSE F&O archive');const rows=parseCsv(await file.buffer());const futures=rows.filter(r=>clean(r.Sgmt)==='FO'&&clean(r.FinInstrmTp)==='STF'&&clean(r.OptnTp)==='XX');const client=await pool.connect();try{await client.query('BEGIN');for(const r of futures){const symbol=clean(r.TckrSymb),expiry=clean(r.XpryDt);if(!symbol||!expiry)continue;await client.query(`INSERT INTO futures_eod(symbol,trade_date,expiry,close,oi,change_oi,instrument_type,contract_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(symbol,trade_date,expiry) DO UPDATE SET close=EXCLUDED.close,oi=EXCLUDED.oi,change_oi=EXCLUDED.change_oi,instrument_type=EXCLUDED.instrument_type,contract_name=EXCLUDED.contract_name`,[symbol,date.toISOString().slice(0,10),expiry,num(r.ClsPric),num(r.OpnIntrst),num(r.ChngInOpnIntrst),clean(r.FinInstrmTp),clean(r.FinInstrmNm)]);}await client.query(`INSERT INTO ingestion_runs(segment,trade_date,status,row_count,schema_version) VALUES('FO',$1,'success',$2,'fo-udiff-v1')`,[date.toISOString().slice(0,10),futures.length]);await client.query('COMMIT');return futures.length;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function main(){const d=new Date();d.setUTCHours(0,0,0,0);for(let i=0;i<7;i++){const x=new Date(d);x.setUTCDate(d.getUTCDate()-i);try{const cm=await ingestCm(x);const fo=await ingestFo(x);console.log(`INGESTED ${x.toISOString().slice(0,10)} CM=${cm} FO=${fo}`);return;}catch(e){console.log(`SKIP ${x.toISOString().slice(0,10)}: ${e.message}`);}}throw new Error('No recent NSE trading-day files were available.');}
if(require.main===module)main().then(()=>pool.end()).catch(e=>{console.error(e);pool.end();process.exit(1)});
module.exports={ingestCm,ingestFo};
