const CFG = require('./config');
const n = v => v == null || v === '' || !Number.isFinite(Number(v)) ? null : Number(v);
const dk = v => v instanceof Date ? v.toISOString().slice(0,10) : v == null ? null : String(v).slice(0,10);
const rowsOf = rows => (Array.isArray(rows) ? rows.slice() : []).sort((a,b)=>(dk(a.trade_date||a.date)||'').localeCompare(dk(b.trade_date||b.date)||''));
function calculateObv(rows){ let obv=0; const out=[]; const rs=rowsOf(rows); for(let i=0;i<rs.length;i++){const c=n(rs[i].close??rs[i].last_price),p=n(i?rs[i-1].close??rs[i-1].last_price:rs[i].prev_close),v=n(rs[i].volume)||0;if(c!==null&&p!==null){if(c>p)obv+=v;else if(c<p)obv-=v}out.push({...rs[i],obv})}return out }
function evaluate({symbol,history=[],current=null,futures=null}={}){
 const rows=rowsOf(history),latest={...(current||rows.at(-1)||{})},date=dk(latest.trade_date||latest.date),hasDerivatives=Boolean(futures&&futures.available),derivativesSupported=Boolean(hasDerivatives||(futures&&futures.derivativesSupported===true)),derivativesState=hasDerivatives?'OI_SUPPORTED_WITH_EVIDENCE':derivativesSupported?'OI_MISSING_UNEXPECTEDLY':'OI_NOT_SUPPORTED',prior=rows.filter(r=>dk(r.trade_date||r.date)!==date);
 const volumeSample=prior.slice(-CFG.historyDays).map(r=>n(r.volume)).filter(v=>typeof v==='number'&&!isNaN(v));
 const avgVolume=volumeSample.length?volumeSample.reduce((a,b)=>a+b,0)/volumeSample.length:0,volume=n(latest.volume),volumeRatio=volume!==null&&avgVolume>0?volume/avgVolume:null;
 const sample=rows.slice(-CFG.deliveryTrendLookback).map(r=>r.deliv_per??r.delivery_pct),validDeliverySamples=sample.filter(r=>typeof r==='number'&&!isNaN(r));
 const avgDelivery=validDeliverySamples.length>0?validDeliverySamples.reduce((a,b)=>a+b,0)/validDeliverySamples.length:0;
 const deliveryPct=n(latest.deliv_per??latest.delivery_pct),deliveryQty=n(latest.deliv_qty??latest.delivery_qty),prevDel=validDeliverySamples.length>1?validDeliverySamples.slice(0,-1):[],prevDelAvg=prevDel.length?prevDel.reduce((a,b)=>a+b,0)/prevDel.length:null,deliveryTrend=deliveryPct!==null&&prevDelAvg!==null?deliveryPct-prevDelAvg:null;
 const close=n(latest.close??latest.last_price),prevClose=n(latest.prev_close),priceChangePct=close!==null&&prevClose!==null&&prevClose!==0?((close/prevClose)-1)*100:null;
 const obvRows=calculateObv(rows),obv=obvRows.length?obvRows.at(-1).obv:null,obvBase=obvRows.length>CFG.obvLookback?obvRows.at(-1-CFG.obvLookback).obv:null,obvTrend=obv!==null&&obvBase!==null?obv-obvBase:null;
 const oiDate=dk(futures?.trade_date||futures?.date),oiExactDate=hasDerivatives&&oiDate===date,futuresOi=oiExactDate?n(futures.oi??futures.open_interest):null,changeOi=oiExactDate?n(futures.change_oi??futures.change_in_oi):null,oiTrend3Day=n(futures?.oiTrend3Day);
 const weights=derivativesSupported?CFG.weights:CFG.cashWeights;
 let rawScore=0,availableWeight=0;const components=[],why=[];const add=(name,w,p,detail)=>{if(p===null)return;rawScore+=p;availableWeight+=w;components.push({name,weight:w,points:Math.round(p*100)/100});if(detail)why.push(detail)};
 if(priceChangePct!==null){const p=priceChangePct>0.5?weights.price:priceChangePct>=0.1?weights.price*0.8:priceChangePct>=-0.2?weights.price*(8/15):0;add('Price stability',weights.price,p,priceChangePct>=-0.2?'Price is stable/tightly based.':'Price is breaking down.')}
 if(volumeRatio!==null){const p=volumeRatio>=1.3?weights.volume:volumeRatio>=1?weights.volume*(2/3):volumeRatio>=0.7?weights.volume*0.4:0;add('Volume expansion',weights.volume,p,`Volume ratio is ${volumeRatio.toFixed(2)}x.`)}
 if(deliveryPct!==null){let p=deliveryPct>=55?weights.delivery:deliveryPct>=45?weights.delivery*(18/25):deliveryPct>=35?weights.delivery*0.4:0;if(deliveryTrend!==null&&deliveryTrend>0)p=Math.min(weights.delivery,p+weights.delivery*0.15);add('Delivery quality',weights.delivery,p,deliveryTrend!==null&&deliveryTrend>0?`Delivery is ${deliveryPct.toFixed(1)}% and trending higher.`:`Delivery is ${deliveryPct.toFixed(1)}%.`)}
 if(obvTrend!==null)add('OBV structure',weights.obv,obvTrend>0?weights.obv:obvTrend===0?weights.obv*0.4:0,obvTrend>0?'OBV trend is rising.':obvTrend===0?'OBV trend is neutral.':'OBV trend is falling.');
 if(hasDerivatives&&(oiExactDate||oiTrend3Day!==null)){const today=changeOi!==null&&changeOi>0,trend=oiTrend3Day!==null&&oiTrend3Day>0,p=today&&trend?CFG.weights.futuresOi:today?CFG.weights.futuresOi*(18/25):trend?CFG.weights.futuresOi*(12/25):changeOi===0?CFG.weights.futuresOi*0.1:0;add('Futures OI action',CFG.weights.futuresOi,p,today?`Futures OI increased on the exact trading date (+${changeOi}).`:trend?'Futures OI trend is positive over three sessions.':`Futures OI change is ${changeOi??'N/A'}.`)}
 const score=derivativesState==='OI_MISSING_UNEXPECTEDLY'?null:(availableWeight?Math.round(rawScore/availableWeight*100):null);
 const turnover=typeof latest.turnover==='number'?latest.turnover:Number(latest.volume||0)*Number(latest.close||0),floor=CFG.safetyFloors||{},safetyFailures=[];
 if(!(turnover>=(floor.minTurnoverRupees||50000000)))safetyFailures.push(`turnover is below ₹${((floor.minTurnoverRupees||50000000)/10000000).toFixed(0)} Cr`);
 if(!(priceChangePct!==null&&priceChangePct>=(floor.minPriceChangePct??-0.2)))safetyFailures.push(`price change is below ${(floor.minPriceChangePct??-0.2).toFixed(2)}%`);
 if(!(deliveryPct!==null&&deliveryPct>=(floor.minDeliveryPct??35)))safetyFailures.push(`delivery is below ${(floor.minDeliveryPct??35).toFixed(1)}%`);
 if(rows.length<CFG.minConfirmedHistory)safetyFailures.push(`history is shorter than ${CFG.minConfirmedHistory} sessions`);
 if(derivativesState==='OI_MISSING_UNEXPECTEDLY')safetyFailures.push('F&O OI data is missing unexpectedly; research state is DATA N/A');
 const pillars={volume:volumeRatio!==null&&(volumeRatio>=1.1||(volumeRatio>=0.8&&deliveryPct!==null&&deliveryPct>=55)),delivery:deliveryPct!==null&&deliveryPct>=45,obv:obvTrend!==null&&obvTrend>0,oi:hasDerivatives&&((changeOi!==null&&changeOi>0)||(oiTrend3Day!==null&&oiTrend3Day>0))};
 const names=derivativesSupported?['volume','delivery','obv','oi']:['volume','delivery','obv'],passed=names.filter(k=>pillars[k]).length,required=derivativesSupported?CFG.quorum.fno.required:CFG.quorum.cash.required;
 const quiet=derivativesState!=='OI_MISSING_UNEXPECTEDLY'&&score!==null&&score>=50&&volumeRatio!==null&&volumeRatio>=0.65&&volumeRatio<=1.05&&deliveryPct!==null&&deliveryPct>=55&&obvTrend!==null&&obvTrend>0&&priceChangePct!==null&&Math.abs(priceChangePct)<=0.5&&safetyFailures.length===0;
 const fallingOi=(changeOi!==null&&changeOi<0)||(oiTrend3Day!==null&&oiTrend3Day<0),distribution=(score!==null&&score<CFG.verdicts.mixed)||(priceChangePct!==null&&priceChangePct<-0.2&&volumeRatio!==null&&volumeRatio>=1.3&&(!derivativesSupported||fallingOi));
 let verdict='MIXED / UNCONFIRMED';if(distribution)verdict='DISTRIBUTION';else if(quiet)verdict='QUIET ABSORPTION';else if(derivativesState!=='OI_MISSING_UNEXPECTEDLY'&&score!==null&&score>=CFG.verdicts.confirmed&&safetyFailures.length===0&&passed>=required)verdict='ACCUMULATION CONFIRMED';else if(derivativesState!=='OI_MISSING_UNEXPECTEDLY'&&score!==null&&score>=CFG.verdicts.starting&&safetyFailures.length===0&&passed>=Math.max(1,required-1)&&passed<required)verdict='ACCUMULATION STARTING';
 if(safetyFailures.length)why.push(`Safety floors not satisfied: ${safetyFailures.join('; ')}.`);if(derivativesState==='OI_NOT_SUPPORTED')why.push('Futures OI is not supported; normalized cash-equity scoring uses Price, Volume, Delivery and OBV.');else if(derivativesState==='OI_MISSING_UNEXPECTEDLY')why.push('Futures OI is supported for this asset but the current session evidence is missing; result is DATA N/A rather than cash-only fallback.');else if(!oiExactDate&&oiTrend3Day===null)why.push('Futures OI confirmation is unavailable for the exact date.');if(deliveryPct===null)why.push('Delivery data is unavailable.');if(volumeRatio===null)why.push('Volume history is insufficient for a reliable ratio.');if(!rows.length)why.push('No verified EOD history is available.');
 return {symbol:String(symbol||latest.symbol||'').toUpperCase(),tradeDate:date,score,verdict,metrics:{close,prevClose,priceChangePct,volume,avgVolume,volumeRatio,deliveryPct,deliveryQty,avgDelivery,deliveryTrend,turnover,obv,obvTrend,futuresOi,changeOi,oiExactDate,oiTrend3Day,hasDerivatives,derivativesSupported,derivativesState},components,why,confirmation:{status:verdict==='ACCUMULATION CONFIRMED'?'confirmed':'blocked',gateFailures:safetyFailures,pillars:{passed,required,total:derivativesSupported?CFG.quorum.fno.total:CFG.quorum.cash.total,details:pillars}}};
}
module.exports={evaluate,calculateObv};
